// Generated by Finicky Kickstart
// https://finicky-kickstart.vercel.app
module.exports = {
  defaultBrowser: "Safari",
  handlers: [
    {
      match: /^https?:\/\/meet\.google\.com\/.*$/,
      browser: "Brave Browser"
    },
    {
      match: /^https?:\/\/localhost.*$/,
      browser: "Google Chrome"
    }
  ]
}
