"
" Needed since our vimrc is not on a user level
" http://stackoverflow.com/questions/5845557/in-a-vimrc-is-set-nocompatible-completely-useless#5845583
set nocompatible

"
" Define Vim's internal shell path
set shell=/bin/sh


"
" Adding these items to the plugin/ directory breaks youcompleteme. wtf?
"
" General
source /Users/bc/.dot-files/vim/vim_settings/vundle.vim
source /Users/bc/.dot-files/vim/vim_settings/functions.vim
source /Users/bc/.dot-files/vim/vim_settings/gui.vim
source /Users/bc/.dot-files/vim/vim_settings/keymap.vim

"Plugin Specific
source /Users/bc/.dot-files/vim/vim_settings/nerd_tree.vim
source /Users/bc/.dot-files/vim/vim_settings/emmet.vim
source /Users/bc/.dot-files/vim/vim_settings/you_complete_me.vim
source /Users/bc/.dot-files/vim/vim_settings/ctrl_p.vim
source /Users/bc/.dot-files/vim/vim_settings/gist.vim
source /Users/bc/.dot-files/vim/vim_settings/snipmate.vim

